import openai
import os
from openai import OpenAI



def generate_response_openai(client, prompt, temperature=0.7, model="gpt-3.5-turbo"):
    """
    Generate a chatbot response using the OpenAI API.

    Args:
        client (OpenAI): The instantiated OpenAI client.
        prompt (str): The user's query or message.
        temperature (float): Controls randomness in the response.
        model (str): The OpenAI model to use (e.g., gpt-3.5-turbo, gpt-4).

    Returns:
        str: The response generated by the AI.
    """
    try:
        # Define the conversation
        messages = [
            {"role": "system", "content": "You are a helpful AI assistant."},
            {"role": "user", "content": prompt},
        ]
        
        # Call the OpenAI API using the new client interface
        response = client.chat.completions.create(
            model=model,
            messages=messages,
            temperature=temperature,
        )

        # Return the assistant's response
        return response.choices[0].message.content.strip()

    except Exception as e:
        return f"An error occurred: {str(e)}"
